apiVersion: v1
kind: Pod
metadata:
  name: busybox
  namespace: "${NAMESPACE}"
  labels:
    app.kubernetes.io/instance: busybox

spec:
  volumes:
    - name: hlf
      nfs:
        path: "${NFS_DIR}"
        server: "${NFS_SERVER}"

  containers:
    - name: busybox
      image: "${REG_URL}/busybox:1.34.1"
      tty: true
      command:
        - sh
        - -c
        - |
          echo "START: \$(ls -l /hlf | wc -l)"
          while [ "\$(ls -l /hlf | wc -l)" != "1" ]; do
            echo "\$(ls -l /hlf | wc -l)"
            rm -rf /hlf/*
            sleep 1
          done
          sh
      volumeMounts:
        - name: hlf
          mountPath: /hlf