apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "hlf-cc.fullname" . }}
  labels:
    {{- include "hlf-cc.labels" . | nindent 4 }}
spec:
  replicas: {{ .Values.replicaCount }}

  selector:
    matchLabels:
      {{- include "hlf-cc.selectorLabels" . | nindent 6 }}

  template:
    metadata:
      labels:
        {{- include "hlf-cc.selectorLabels" . | nindent 8 }}

    spec:
      containers:
        - name: {{ .Chart.Name }}
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag | default .Chart.AppVersion }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          ports:
            - name: cc-port
              containerPort: {{ .Values.service.port }}
              protocol: TCP
          envFrom:
            - configMapRef:
                name: {{ include "hlf-cc.fullname" . }}-env