apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "hl-explorer.fullname" . }}
  labels:
    {{- include "hl-explorer.labels" . | nindent 4 }}
spec:
  replicas: {{ .Values.replicaCount }}

  selector:
    matchLabels:
      {{- include "hl-explorer.selectorLabels" . | nindent 6 }}

  template:
    metadata:
      {{- with .Values.podAnnotations }}
      annotations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      labels:
        {{- include "hl-explorer.selectorLabels" . | nindent 8 }}
    spec:

      volumes:
        - name: data
          persistentVolumeClaim:
            claimName: {{ include "hl-explorer.fullname" . }}
        - name: test-network
          configMap:
            name: {{ include "hl-explorer.fullname" . }}

      containers:
        - name: {{ .Chart.Name }}
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag | default .Chart.AppVersion }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          env:
            - name: LOG_LEVEL_APP
              value: debug
            - name: LOG_LEVEL_DB
              value: debug
            - name: LOG_LEVEL_CONSOLE
              value: info
            - name: LOG_CONSOLE_STDOUT
              value: "true"
            - name: DISCOVERY_AS_LOCALHOST
              value: "false"
            - name: DATABASE_HOST
              value: {{ .Values.hlExplorer.db.host }}
            - name: DATABASE_DATABASE
              value: {{ .Values.hlExplorer.db.dbName }}
            - name: DATABASE_USERNAME
              value: {{ .Values.hlExplorer.db.user }}
            - name: DATABASE_PASSWD
              value: {{ .Values.hlExplorer.db.pass }}
          ports:
            - name: http
              containerPort: {{ .Values.service.port }}
              protocol: TCP
          livenessProbe:
            httpGet:
              path: /
              port: http
          readinessProbe:
            httpGet:
              path: /
              port: http
          volumeMounts:
            - name: data
              mountPath: {{ .Values.hlExplorer.config.mountBaseDir }}
            - name: test-network
              mountPath: /opt/explorer/app/platform/fabric/connection-profile
          resources:
            {{- toYaml .Values.resources | nindent 12 }}
      {{- with .Values.nodeSelector }}
      nodeSelector:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.affinity }}
      affinity:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.tolerations }}
      tolerations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
