# Copyright IBM Corp. All Rights Reserved.
#
# SPDX-License-Identifier: Apache-2.0
#

---
################################################################################
#
#   Section: Organizations
#
#   - This section defines the different organizational identities which will
#   be referenced later in the configuration.
#
################################################################################
Organizations:
    - &Org${ORG_ID}
        # DefaultOrg defines the organization which is used in the sampleconfig
        # of the fabric.git development environment
        Name: Org${ORG_ID}MSP

        # ID to load the MSP definition as
        ID: Org${ORG_ID}MSP

        MSPDir: ../organizations/peerOrganizations/org${ORG_ID}.example.com/msp

        Policies:
            Readers:
                Type: Signature
                Rule: "OR('Org${ORG_ID}MSP.admin', 'Org${ORG_ID}MSP.peer', 'Org${ORG_ID}MSP.client')"
            Writers:
                Type: Signature
                Rule: "OR('Org${ORG_ID}MSP.admin', 'Org${ORG_ID}MSP.client')"
            Admins:
                Type: Signature
                Rule: "OR('Org${ORG_ID}MSP.admin')"
            Endorsement:
                Type: Signature
                Rule: "OR('Org${ORG_ID}MSP.peer')"
