apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "hlf-peer.fullname" . }}-env
  labels:
  {{- include "hlf-peer.labels" . | nindent 4 }}
data:
  FABRIC_LOGGING_SPEC: "INFO"
  CORE_PEER_TLS_ENABLED: "true"
  CORE_PEER_TLS_CERT_FILE: "{{ .Values.hlfPeer.config.mountBaseDir }}/{{ .Values.hlfPeer.config.cmpDir }}/tls/server.crt"
  CORE_PEER_TLS_KEY_FILE: "{{ .Values.hlfPeer.config.mountBaseDir }}/{{ .Values.hlfPeer.config.cmpDir }}/tls/server.key"
  CORE_PEER_TLS_ROOTCERT_FILE: "{{ .Values.hlfPeer.config.mountBaseDir }}/{{ .Values.hlfPeer.config.cmpDir }}/tls/ca.crt"
  # Peer Specific Variables
  CORE_PEER_ID: {{ .Values.hlfPeer.config.fqdn | quote }}
  CORE_PEER_ADDRESSAUTODETECT: "true"
  CORE_PEER_ADDRESS: "{{ .Values.hlfPeer.config.fqdn }}:{{ .Values.service.port }}"
  CORE_PEER_LISTENADDRESS: "0.0.0.0:{{ .Values.service.port }}"
  CORE_PEER_CHAINCODEADDRESS: "{{ .Values.hlfPeer.config.fqdn }}:{{ .Values.hlfPeer.chaincode.port }}"
  CORE_PEER_CHAINCODELISTENADDRESS: "0.0.0.0:{{ .Values.hlfPeer.chaincode.port }}"
  CORE_PEER_GOSSIP_BOOTSTRAP: "{{ .Values.hlfPeer.config.fqdn }}:{{ .Values.service.port }}"
  CORE_PEER_GOSSIP_EXTERNALENDPOINT: "{{ .Values.hlfPeer.config.fqdn }}:{{ .Values.service.port }}"
  CORE_PEER_LOCALMSPID: "{{ .Values.hlfPeer.config.mspId }}"
  CORE_PEER_MSPCONFIGPATH: "{{ .Values.hlfPeer.config.mountBaseDir }}/{{ .Values.hlfPeer.config.cmpDir }}/msp"
  CORE_PEER_FILESYSTEMPATH: "{{ .Values.hlfPeer.config.mountBaseDir }}/{{ .Values.hlfPeer.config.cmpDir }}/ledger"
  # CouchDB Variables
  CORE_LEDGER_STATE_STATEDATABASE: "CouchDB"
  CORE_LEDGER_STATE_COUCHDBCONFIG_COUCHDBADDRESS: "localhost:{{ .Values.hlfPeer.couchdb.port }}"
  CORE_LEDGER_STATE_COUCHDBCONFIG_USERNAME: {{ .Values.hlfPeer.couchdb.user | quote }}
  CORE_LEDGER_STATE_COUCHDBCONFIG_PASSWORD: {{ .Values.hlfPeer.couchdb.pass | quote}}
  # Misc
  ADMIN_MSP_DIR: "{{ .Values.hlfPeer.config.mountBaseDir }}/{{ .Values.hlfPeer.config.adminMspDir }}"
