apiVersion: v1
kind: Service
metadata:
  name: {{ include "hlf-peer.fullname" . }}
  labels:
    {{- include "hlf-peer.labels" . | nindent 4 }}
spec:
  type: {{ .Values.service.type }}
  ports:
    - port: {{ .Values.service.port }}
      targetPort: {{ .Values.service.port }}
      {{- if eq .Values.service.type "NodePort" }}
      nodePort: {{ .Values.service.port }}
      {{- end }}
      protocol: TCP
      name: peer-port
  selector:
    {{- include "hlf-peer.selectorLabels" . | nindent 4 }}
